name: cron
on:
  schedule:
    - cron: "0 0 * * 0" # @weekly https://crontab.guru/
jobs:
  test:
    name: Regular security audit and fitness function verification
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: 13
      - run: yarn install
      - run: yarn audit-ci
      - run: yarn libyear -D=1 -P=10
